Tutorial/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tutorial.Models;
using Tutorial.DAL;

namespace Tutorial.Controllers
{   
    public class DepartmentController : Controller
    {
        private ApplicationDb context = new ApplicationDb();

        //
        // GET: /Department/

        public ViewResult Index()
        {
            return View(context.Departments.ToList());
        }

        //
        // GET: /Department/Details/5

        public ViewResult Details(int id)
        {
            Department department = context.Departments.Single(x => x.Id == id);
            return View(department);
        }

        //
        // GET: /Department/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Department/Create

        [HttpPost]
        public ActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                context.Departments.Add(department);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(department);
        }
        
        //
        // GET: /Department/Edit/5
 
        public ActionResult Edit(int id)
        {
            Department department = context.Departments.Single(x => x.Id == id);
            return View(department);
        }

        //
        // POST: /Department/Edit/5

        [HttpPost]
        public ActionResult Edit(Department department)
        {
            if (ModelState.IsValid)
            {
                context.Entry(department).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        //
        // GET: /Department/Delete/5
 
        public ActionResult Delete(int id)
        {
            Department department = context.Departments.Single(x => x.Id == id);
            return View(department);
        }

        //
        // POST: /Department/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = context.Departments.Single(x => x.Id == id);
            context.Departments.Remove(department);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tutorial/Views/Shared/Gentelella/_MenuAdminPartial.cshtml
@using System.Configuration

@{ 
    string ProjectName = "Gentellela Alela";


    if ( ConfigurationManager.AppSettings["ProjectName"] != null)
    {
        ProjectName = ConfigurationManager.AppSettings["ProjectName"];
    }
}
<div class="navbar nav_title" style="border: 0;">
    <a href="@Url.Action("Admin", "Home")" class="site_title"><i class="fa fa-gear"></i> 
        <span>@ProjectName</span>
    </a>
</div>

<div class="clearfix"></div>

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
            <li>
                <a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="@Url.Action("Admin", "Home")">Dashboard</a></li>
                </ul>
            </li>
            <li>
                <a><i class="fa fa-edit"></i> Master <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="form.html">Account</a></li>
                    <li><a href="@Url.Action("Index","Customer")">Customer</a></li>
                    <li><a href="@Url.Action("Index","Department")">Department</a></li>
                </ul>
            </li>
        </ul>
    </div>    
</div>
<!-- /sidebar menu -->
<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>
<!-- /menu footer buttons -->